export class MainPageConstants {
  // 主页底部导航栏图标与标题的间距
  static readonly TAB_SPACE: number = 2;

  // 百分之百宽
  static readonly FULL_WIDTH: string = "100%";

  // 百分之百高
  static readonly FULL_HEIGHT: string = "100%";

  // 字体粗度500
  static readonly FONT_WEIGHT_500: number = 500;

  // 字体粗度700
  static readonly FONT_WEIGHT_700: number = 700;

  // 字体大小22fp
  static readonly FONT_SIZE_22: string = "22fp";

  // 字体大小16fp
  static readonly FONT_SIZE_16: string = "16fp";

  // 透明度100%
  static readonly FULL_OPACITY: number = 1;

  // 透明度0.8
  static readonly EIGHTY_OPACITY: number = 0.8;

  // 宽高比
  static readonly ASPECT_RATIO: number = 2;

  static readonly VP_6: string = "-6vp";

  static readonly VP_5: string = "5vp";

  static readonly VP_30: string = "30vp";

  static readonly VP_80: string = "80vp";

  static readonly VP_40: string = "40vp";

  static readonly VP_20: string = "20vp";

  static readonly VP_12: string = "12vp";

  static readonly VP_120: string = "120vp";

  static readonly VP_280: string = "280vp";
}